<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="piecewiseconstant"
    nsURI="http://lextpf.github.io/birt/chart/PiecewiseConstantModelType" nsPrefix="piecewise">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Schema file for the piecewise constant chart model package. A piecewise constant series is also known as a step line, a staircase or a zero-order-hold series."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="PiecewiseConstantSeries" eSuperTypes="http://www.birt.eclipse.org/ChartModelType#//LineSeries">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This is a Series type that holds the query data for piecewise constant charts during design time, and the value for each data point during run time. When rendered, consecutive data points are joined by horizontal and vertical segments instead of a direct line."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="PiecewiseConstantSeries"/>
      <details key="kind" value="elementOnly"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stepMode" eType="#//StepMode"
        defaultValueLiteral="After" unsettable="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Specifies where the line jumps from one value to the next."/>
      </eAnnotations>
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="StepMode"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StepMode">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This type represents the possible positions of the step between two data points."/>
    </eAnnotations>
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="name" value="StepMode"/>
    </eAnnotations>
    <eLiterals name="After"/>
    <eLiterals name="Before" value="1"/>
    <eLiterals name="Center" value="2"/>
  </eClassifiers>
</ecore:EPackage>
